project:
  type: website
  output-dir: docs

website:
  title: "Devin P. Merullo, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: About
      - projects.qmd
      - resume.qmd
      - misc.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



