project:
  type: website
  output-dir: docs

website:
  title: "dmerullo.github.io"
  navbar:
    left:
      - href: index.qmd
        text: About
      - projects.qmd
      - resume.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



