---
title: "Projects"
---

<style>
body {
text-align: justify}
</style>

***

# Natural language and data science

I developed [Project ESPAÑOL](https://github.com/dmerullo/project-espanol){target="_blank"}, an application that leverages high-dimensional analysis of classical Spanish-language poems to create custom lesson plans and guide discovery of new texts for practice and study. Using high-throughput web scraping, I generated a dataset of 10,000 Spanish-language poems in the public domain (totaling 2.5 million words), and then ran an unsupervised clustering algorithm in Python to group the poems into difficulty levels by analyzing verb frequencies and grammatical tenses. I built [an interactive Plotly Dash application](http://dmerullo.pythonanywhere.com/){target="_blank"} to view the full texts, metadata, and grammatical statistics.

# Biomarkers and genomic medicine

*at [Parexel International](https://en.wikipedia.org/wiki/Parexel){target="_blank"}*

At a clinical research organization for a major pharmaceutical client, I performed data ingestion and developed ETL pipelines for external genomic data integration (primarily GWAS & eQTL data). I wrote a variety of pipelines in R, Python, and Bash to streamline data ingestion according to the client's specific data and metadata standards. With fluency in techniques from both bioinformatics and data science, I bridged the scientific analysts who required management of this data at scale, and the data engineers who lacked familiarity with bioinformatics methods and resources.

*Example of open-source tool created:*

- [SPUR: SNP Position Update from rsIDs](https://github.com/dmerullo/rsid-liftover-to-hg38){target="_blank"}
  - A pipeline to lift over genomic coordinates from datasets on older builds of the human genome only containing rsIDs
  - SPUR first identifies the rsIDs in the original data that map to the current dbSNP build without issue, and those that do not. Then,   SPUR differentiates between the non-mapping rsIDs that have been merged to a different rsID in the current build, and the rsIDs that have been dropped completely. Finally, SPUR updates the SNP positions in the original dataset by linking the mapped and merged rsIDs with current genome positions.

# Neural cell types and circuits for vocal learning

*at [University of Texas Southwestern Medical Center](https://en.wikipedia.org/wiki/University_of_Texas_Southwestern_Medical_Center){target="_blank"} in the [Roberts lab](https://labs.utsouthwestern.edu/roberts-lab){target="_blank"} and [Konopka lab](https://konopkalab.org/){target="_blank"}*

My post-doctoral research used comparative high-throughput transcriptomics to understand how the brain produces complex, learned behaviors like speech and language. These projects were the first to implement single-cell RNA sequencing in songbirds, and the results have broad implications for understanding the genetic toolkits that neurons and circuits use to perform advanced computations. I performed end-to-end analysis of large-scale, high-dimensional gene expression data encompassing molecular library preparation, computational pipelines, dataset integration, unsupervised clustering, and statistical modeling. 

*Open-access links to publications:*

-   [(2021) Cellular transcriptomics reveals evolutionary identities of songbird vocal circuits](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8136249/){target="_blank"}
-   [(2021) Expression of FoxP2 in the basal ganglia regulates vocal motor sequences in the adult songbird](https://doi.org/10.1038/s41467-021-22918-2){target="_blank"}

# Neuromodulators of motivation and reward in vocal communication

*at [University of Wisconsin-Madison](https://en.wikipedia.org/wiki/University_of_Wisconsin%E2%80%93Madison){target="_blank"} in the [Riters lab](https://integrativebiology.wisc.edu/staff/riters-lauren/){target="_blank"}*

My doctoral dissertation examined the neural control of vocal communication across contexts, using songbirds as a model system. I identified neurotensin, a neuropeptide involved in motivation and reward that strongly interacts with dopamine, as a potential modulator of context-specific vocalizations. I applied multiple linear regression techniques to analyze datasets containing gene expression, protein labeling, and behavioral observations.

*Open-access links to publications:*

-   [(2018) Neurotensin and neurotensin receptor 1 mRNA expression in song-control regions changes during development in male zebra finches](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6023781/){target="_blank"}
-   [(2018) Co-localization patterns of neurotensin receptor 1 and tyrosine hydroxylase in brain regions involved in motivation and social behavior in male European starlings](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5924578/){target="_blank"}
-   [(2016) Song in an affiliative context relates to the neural expression of dopamine- and neurotensin-related genes in male European starlings](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5121024/){target="_blank"}
-   [(2015) Neurotensin neural mRNA expression correlates with vocal communication and other highly-motivated social behaviors in male European starlings](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4586409/){target="_blank"}
-   [(2015) Neurotensin immunolabeling relates to sexually-motivated song and other social behaviors in male European starlings (*Sturnus vulgaris*)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4361869/){target="_blank"}
