---
title: "Resume"
---

***

### SUMMARY

Ph.D.-trained biomedical data scientist with expertise in bioinformatics, data pipeline development, and high-dimensional analytics. Experienced in next-generation sequencing analysis (bulk, single-cell, spatial), multi-omic data integration, scalable workflow automation, statistical modeling, and data visualization. Effective collaborator and communicator with a proven record of delivering results and solving complex bioinformatics challenges in industry settings.

### EDUCATION

- **Ph.D., Integrative Biology –** University of Wisconsin-Madison (2018)
- **B.S., Biopsychology (*cum laude*) –** Tufts University (2013)

### TECHNICAL SKILLS

- **Programming:** R, Python, Bash, SQL, Julia, Git, Markdown, LaTeX
- **NGS Analysis:** RNA-seq, single-cell sequencing, spatial transcriptomics, clustering (UMAP, tSNE), PCA, tree-based models, differential expression testing, linear mixed models, multiple linear regression, 10X Genomics Chromium, 10X Genomics Visium, Cell Ranger, Space Ranger, Seurat
- **Libraries:** tidyverse, ggplot2, shiny, quarto, pandas, Numpy, SciPy, scikit-learn, Plotly, Dash
- **HPC/Cloud Computing:** Linux, GCP, HDFS

### EXPERIENCE

**Senior Bioinformatics Scientist** (Jan. 2022 – Present)\
**Parexel International**  (Remote)

- Reduce latency of data delivery by 10x for a major pharmaceutical client by creating novel data ingestion pipelines in R, Python, and Bash to drive biomarker discovery
- Collaborate across the bioinformatics and data engineering teams to deliver 1000s of genomic datasets (GWAS & xQTL) scaling to terabytes in size, integrating data and metadata  from UK Biobank, 1000 Genomes Project, FinnGen, Open Targets, GWAS Catalog, and more
- Automate high-throughput quality control workflows to enable 24-hour client turnaround

**Postdoctoral Researcher** (Jun. 2018 – Jan. 2022) \
**University of Texas Southwestern Medical Center**  (Hybrid from Dallas, TX)
  
- Led a multi-group collaboration to publish novel single-cell RNA-seq datasets in neurobiology, resulting in a co-first-author paper in *Science* (145+ citations) and a second-author paper in *Nature Communications* (30+ citations)
- Developed computational and analytical pipelines for large-scale transcriptomics data containing gene expression levels for 20,000+ genes in 200,000+ individual cells across multiple brain regions, species, and experiments
- Delivered end-to-end spatial transcriptomics to research group, encompassing molecular library preparation, data and analytics pipelines, and documentation and training for new users

### INDEPENDENT PROJECTS

**Project ESPAÑOL** [(https://github.com/dmerullo/project-espanol)](https://github.com/dmerullo/project-espanol){target="_blank"}

- Generated a dataset of 10,000+ Spanish-language poems (>2.5 million words) using high-throughput web scraping (rvest)
- Developed an unsupervised clustering pipeline in Python to classify poems into 4 difficultly levels based on verb usage
- Built an interactive Plotly Dash web application for text exploration and visualization
  
### SELECTED PUBLICATIONS (650+ citations total)

- Colquitt, B. M.\*, <strong>Merullo, D. P.\*</strong>, Konopka, G., Roberts, T. F., & Brainard, M. S. (2021). Cellular transcriptomics reveals evolutionary identities of songbird vocal circuits. *Science*, 371(6530), eabd9704. <strong>*co-first author</strong>

- Xiao, L., **Merullo, D. P.**, Koch, T. M. I., Cao, M., Co, M., Kulkarni, A., Konopka, G., & Roberts, T. F. (2021). Expression of FoxP2 in the basal ganglia regulates vocal motor sequences in the adult songbird. *Nature Communications*, 12(1), 2617.

- Kulkarni, A., Anderson, A. G., **Merullo, D. P.**, & Konopka, G. (2019). Beyond bulk: A review of single cell transcriptomics methodologies and applications. *Current Opinion in Biotechnology*, 58, 129–136.

- **Merullo, D. P.**, Asogwa, C. N., Sanchez-Valpuesta, M., Hayase, S., Pattnaik, B. R., Wada, K., & Riters, L. V. (2018). Neurotensin and neurotensin receptor 1 mRNA expression in song-control regions changes during development in male zebra finches. *Developmental Neurobiology*, 78(7), 671–686.

- **Merullo, D. P.**, Spool, J. A., Zhao, C., & Riters, L. V. (2018). Co-localization patterns of neurotensin receptor 1 and tyrosine hydroxylase in brain regions involved in motivation and social behavior in male European starlings. *Journal of Chemical Neuroanatomy*, 89, 1–10.

- **Merullo, D. P.**, Angyal, C. S., Stevenson, S. A., & Riters, L. V. (2016). Song in an affiliative context relates to the neural expression of dopamine- and neurotensin-related genes in male European starlings. *Brain, Behavior and Evolution*, 88, 81–92.

- **Merullo, D. P.**, Cordes, M. A., DeVries, M. S., Stevenson, S. A., & Riters, L. V. (2015). Neurotensin neural mRNA expression correlates with vocal communication and other highly-motivated social behaviors in male European starlings. *Physiology and Behavior*, 151, 155–161.

- **Merullo, D. P.**, Cordes, M. A., Stevenson, S. A., & Riters, L. V. (2015). Neurotensin immunolabeling relates to sexually-motivated song and other social behaviors in male European starlings (Sturnus vulgaris). *Behavioural Brain Research*, 282, 133–143. 

### SELECTED AWARDS ($350,000+ total)

- 2019 – NIH NINDS Postdoctoral Individual NRSA (F32) 
- 2016 – NSF Graduate Research Opportunities Worldwide (GROW)
- 2016 – Japan Society for the Promotion of Science Strategic Fellowship for Overseas Researchers
- 2015 – NSF Graduate Research Fellowship Program (GRFP)